export const CATEGORY_OPTIONS = [
  {
    id: "gastronomia",
    label: "Gastronomía",
    emoji: "🍽️",
    subtags: [
      "Mexicana",
      "China",
      "Italiana",
      "Típica",
      "Vegetariana",
      "Vegana",
      "Heladería",
      "Japonesa",
      "Cafetería",
    ],
    focuses: ["Familiar", "Casual", "Premium", "Rápido"],
    price: {
      hasFreeOption: false,
      min: 0,
      max: 1000,
      step: 50,
      defaultValue: 150,
    },
  },
  {
    id: "entretenimiento",
    label: "Entretenimiento",
    emoji: "🎮",
    subtags: ["Arcade", "Cine", "Karaoke", "Boliche", "Bar", "Billar"],
    focuses: ["Social", "Nocturno", "Familiar", "Casual"],
    price: {
      hasFreeOption: false,
      min: 0,
      max: 1000,
      step: 50,
      defaultValue: 200,
    },
  },
  {
    id: "naturaleza",
    label: "Naturaleza",
    emoji: "🌿",
    subtags: ["Parque", "Bosque", "Mirador", "Jardín", "Lago"],
    focuses: ["Relajado", "Familiar", "Activo", "Escénico"],
    price: {
      hasFreeOption: true,
      min: 0,
      max: 300,
      step: 20,
      defaultValue: 0,
    },
  },
  {
    id: "deportes",
    label: "Deportes",
    emoji: "⚽",
    subtags: ["Gym", "Fútbol", "Pádel", "Basquetbol", "Natación"],
    focuses: ["Activo", "Competitivo", "Formativo", "Social"],
    price: {
      hasFreeOption: false,
      min: 0,
      max: 1000,
      step: 50,
      defaultValue: 150,
    },
  },
  {
    id: "arte_cultura",
    label: "Arte y cultura",
    emoji: "🎨",
    subtags: ["Museo", "Galería", "Teatro", "Centro cultural"],
    focuses: ["Cultural", "Creativo", "Académico", "Patrimonial"],
    price: {
      hasFreeOption: true,
      min: 0,
      max: 500,
      step: 25,
      defaultValue: 0,
    },
  },
  {
    id: "aprendizaje",
    label: "Aprendizaje",
    emoji: "📚",
    subtags: ["Biblioteca", "Cursos", "Talleres", "Idiomas"],
    focuses: ["Académico", "Práctico", "Formativo", "Creativo"],
    price: {
      hasFreeOption: true,
      min: 0,
      max: 500,
      step: 25,
      defaultValue: 0,
    },
  },
  {
    id: "compras",
    label: "Compras",
    emoji: "🛍️",
    subtags: ["Ropa", "Tecnología", "Hogar", "Souvenirs"],
    focuses: ["Práctico", "Premium", "Casual", "Local"],
    price: {
      hasFreeOption: false,
      min: 0,
      max: 2000,
      step: 100,
      defaultValue: 300,
    },
  },
  {
    id: "servicios",
    label: "Servicios",
    emoji: "🧰",
    subtags: ["Salud", "Banco", "Lavandería", "Estética"],
    focuses: ["Práctico", "Rápido", "Profesional", "Local"],
    price: {
      hasFreeOption: false,
      min: 0,
      max: 2000,
      step: 100,
      defaultValue: 200,
    },
  },
  {
    id: "hospedaje",
    label: "Hospedaje",
    emoji: "🏨",
    subtags: ["Hotel", "Hostal", "Cabaña", "Airbnb"],
    focuses: ["Familiar", "Premium", "Económico", "Romántico"],
    price: {
      hasFreeOption: false,
      min: 0,
      max: 5000,
      step: 100,
      defaultValue: 800,
    },
  },
];